/content/documents/myproject/products:
  .meta:order-before: newsfacets
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c0572228-ae66-4c57-86ea-58aaf9260de1
  hippostd:foldertype: [new-product-folder, new-product-document]
  hippotranslation:id: d070fdf5-51f0-424e-a7b6-b5245405da9d
  hippotranslation:locale: en
  /product-1:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: b09658d8-4051-4115-a00d-0b3566792532
    hippo:name: product 1
    hippo:versionHistory: d9c2c8be-a279-4c1d-9923-842c34974670
    /product-1[1]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a9426a07-4c01-42fa-bf12-956f3270f48c
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:08:50.115+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:08:50.115+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 51272b54-218a-4712-a19b-c0d19e99fe36
      hippotranslation:locale: en
      myproject:introduction: product 1 introduction
      myproject:price: 40.1
      myproject:title: product 1
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 1 description</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: de7af505-786c-44a4-bfda-59cfbd31c449
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /product-1[2]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 85a634e7-af82-4409-8338-bb451ede9b5d
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:08:50.115+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:09:36.141+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 51272b54-218a-4712-a19b-c0d19e99fe36
      hippotranslation:locale: en
      myproject:introduction: product 1 introduction
      myproject:price: 40.1
      myproject:title: product 1
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 1 description</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: de7af505-786c-44a4-bfda-59cfbd31c449
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /product-1[3]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 7bd63f5b-633e-493a-a4ab-c51f6634202c
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:08:50.115+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:09:36.141+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-09-25T17:09:43.453+02:00
      hippotranslation:id: 51272b54-218a-4712-a19b-c0d19e99fe36
      hippotranslation:locale: en
      myproject:introduction: product 1 introduction
      myproject:price: 40.1
      myproject:title: product 1
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 1 description</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: de7af505-786c-44a4-bfda-59cfbd31c449
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /product-2:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 2b3ef017-1a65-48c0-b064-da7aac6d63db
    hippo:name: product 2
    hippo:versionHistory: ae9903cd-1cb2-47cc-be1a-219bced1036c
    /product-2[1]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 6188600b-90bd-41ee-bf92-4e244e6f817e
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:09:59.969+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:09:59.969+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: c5fe521e-5254-4502-a6b9-2a679106786b
      hippotranslation:locale: en
      myproject:introduction: product 2
      myproject:price: 80.0
      myproject:title: product 2
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 2</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: be419974-c2bd-4d6b-a022-8b95967a6f7e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /product-2[2]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 31d599e3-a3ba-436a-869a-82bac03567c0
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:09:59.969+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:10:13.383+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: c5fe521e-5254-4502-a6b9-2a679106786b
      hippotranslation:locale: en
      myproject:introduction: product 2
      myproject:price: 80.0
      myproject:title: product 2
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 2</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: be419974-c2bd-4d6b-a022-8b95967a6f7e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /product-2[3]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 2f94840d-02b0-4c17-a28b-e4030f99a73c
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:09:59.969+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:10:13.383+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-09-25T17:10:16.381+02:00
      hippotranslation:id: c5fe521e-5254-4502-a6b9-2a679106786b
      hippotranslation:locale: en
      myproject:introduction: product 2
      myproject:price: 80.0
      myproject:title: product 2
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>product 2</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: be419974-c2bd-4d6b-a022-8b95967a6f7e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /family-tant:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: b7c9dbf7-3229-4c6d-bbc1-29dd4249a032
    hippo:name: family tant
    hippo:versionHistory: 71856232-e774-4cbe-8c52-76b7e4890710
    /family-tant[1]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 34687b45-bfc0-4773-a952-c2232b79b4be
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:10:29.061+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:10:29.061+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 008adf52-4f10-4013-bda5-8e63841028ad
      hippotranslation:locale: en
      myproject:introduction: family tant
      myproject:price: 150.0
      myproject:title: family tant
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>family tant</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 70ce308a-7c1d-4244-ada2-f679fca92608
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /family-tant[2]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: b0ca0f11-5d5f-4746-a217-a7ebaf287229
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:10:29.061+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:10:40.341+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 008adf52-4f10-4013-bda5-8e63841028ad
      hippotranslation:locale: en
      myproject:introduction: family tant
      myproject:price: 150.0
      myproject:title: family tant
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>family tant</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 70ce308a-7c1d-4244-ada2-f679fca92608
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /family-tant[3]:
      jcr:primaryType: myproject:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 53104d4d-463f-406d-a1eb-e0957bb35ce6
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2021-09-25T17:10:29.061+02:00
      hippostdpubwf:lastModificationDate: 2021-09-25T17:10:40.341+02:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2021-09-25T17:10:43.008+02:00
      hippotranslation:id: 008adf52-4f10-4013-bda5-8e63841028ad
      hippotranslation:locale: en
      myproject:introduction: family tant
      myproject:price: 150.0
      myproject:title: family tant
      /myproject:description:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>family tant</p>
      /myproject:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 70ce308a-7c1d-4244-ada2-f679fca92608
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
