definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/homepage
            hst:pagetitle: Home Page
            hst:refId: root
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
          /pagenotfound:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:pagetitle: Not Found Page
            hst:refId: pagenotfound
          /news:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/newslist
            hst:pagetitle: List of News Items
            hst:relativecontentpath: newsfacets
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/newspage
              hst:relativecontentpath: news/${1}
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/newslist
              hst:relativecontentpath: ${parent}/${1}
          /search:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/search
            hst:pagetitle: Search Results
            hst:refId: search
          /content:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/contentlist
            hst:pagetitle: List of Simple Documents
            hst:relativecontentpath: content
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/contentpage
              hst:relativecontentpath: ${parent}/${1}
            /_any_:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/contentlist
              hst:relativecontentpath: ${parent}/${1}
          /products:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/productslist
            hst:relativecontentpath: products
            /_any_.html:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/productpage
              hst:relativecontentpath: ${parent}/${1}
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/pagenotfound-main.ftl
          /newspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/newspage-main.ftl
          /search-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/search-main.ftl
          /contentlist-main-contentlist:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/contentlist-main-contentlist.ftl
          /twocolumns-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/twocolumns-main.ftl
          /newspage-relatednews:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/newspage-relatednews.ftl
          /twocolumns-right-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/twocolumns-right-menu.ftl
          /productslist:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/productslist.ftl
          /productpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/productpage-main.ftl
          /featured-products:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/featured-products.ftl
          /faceted-navigation:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/faceted-navigtion.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /myproject-catalog:
            jcr:primaryType: hst:containeritempackage
            /featured-products:
              jcr:primaryType: hst:componentdefinition
              hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsListPickerComponent
              hst:label: Featured Products
              hst:template: featured-products
      /myproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /cn-project:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
