definitions:
  config:
    /hippo:namespaces/myproject/product:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 91998a51-3ac5-4952-8418-84f58978324f
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 7c6a409c-60de-48d5-a1a6-b17366a5298c
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: d4ca79c4-9977-4936-af27-b936c3adcd33
          hipposysedit:node: true
          hipposysedit:supertype: ['myproject:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.myproject.com/myproject/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /price:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:price
            hipposysedit:primary: false
            hipposysedit:type: Double
            hipposysedit:validators: [required]
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required]
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            hipposysedit:validators: [required]
          /images:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: myproject:images
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [required]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:product
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          myproject:title: ''
          myproject:price: 0.0
          myproject:introduction: ''
          jcr:uuid: 3278df73-868c-41cd-a150-228fa628cfe8
          hippostdpubwf:lastModificationDate: 2021-09-25T16:59:00.164+02:00
          hippostdpubwf:creationDate: 2021-09-25T16:59:00.165+02:00
          /myproject:description:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /myproject:images:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /price:
            jcr:primaryType: frontend:plugin
            caption: Price
            field: price
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            caption: Introduction
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: Description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /images:
            jcr:primaryType: frontend:plugin
            caption: images
            field: images
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
